import fs from 'node:fs';
import { createNexVisualHandoff } from '../integrations/nex_visual_handoff_contract.js';
import { runNexResearchHandoffPipeline, runCanonicalVisualPipeline } from '../pipeline/visual_pipeline.js';
const validInput={research_id:'research-apis-scale',title:'Why APIs fail at scale',original_question:'Why do APIs fail at scale?',executive_summary:'Systems failure narrative: Nex verified claims for visual interpretation.',verified_findings:[{finding_id:'F1',claim:'Latency compounds through dependency chains.',finding_confidence:'VERIFIED',evidence_ids:['E1']},{finding_id:'F2',claim:'Queues saturate shared resources.',finding_confidence:'VERIFIED',evidence_ids:['E2']},{finding_id:'F3',claim:'Retries can amplify cascading failure.',finding_confidence:'LIKELY',evidence_ids:['E3']}],concept_relationships:[{from:'F1',to:'F2',relationship:'causal sequence'}],evidence_items:[{evidence_id:'E1',source_id:'S1',text:'Latency compounds through dependency chains.'},{evidence_id:'E2',source_id:'S2',text:'Queues saturate shared resources.'},{evidence_id:'E3',source_id:'S3',text:'Retries can amplify cascading failure.'}],source_references:[{source_id:'S1',title:'Source 1',url:'https://example.com/1'},{source_id:'S2',title:'Source 2',url:'https://example.com/2'},{source_id:'S3',title:'Source 3',url:'https://example.com/3'}],visual_objective:'Systems failure narrative',audience:'general technical audience',artifact_type:'slide_artifact'};
function run(input){return runNexResearchHandoffPipeline(createNexVisualHandoff(input));}
const result=run(validInput); fs.writeFileSync('outputs/nex-verification/valid-nex-result.json', JSON.stringify(result,null,2));
const runs=[run(validInput),run(validInput),run(validInput)].map(r=>({handoff_id:r.handoff_id,scene_graph_hash:r.scene_graph.scene_graph_hash,timeline_hash:r.timeline.timeline_hash,render_contract_hash:r.render_contract.contract_hash,artifact_hash:r.artifact.artifact_hash,slide_count:r.artifact.slide_count}));
fs.writeFileSync('outputs/nex-verification/determinism.json', JSON.stringify(runs,null,2));
const cases={missing_required:{...validInput,research_id:''},malformed_value:{...validInput,verified_findings:[{finding_id:'F1',claim:'x',finding_confidence:'BOGUS',evidence_ids:['E1']}]},unknown_entity:{...validInput,selected_finding_id:'NOPE'},empty_input:{},unsupported_version:{...validInput,schema_version:'9.9.9'},duplicate_input:{...validInput,verified_findings:[validInput.verified_findings[0],validInput.verified_findings[0]]},partial_input:{...validInput,evidence_items:[]}};
const failures={}; for (const [name,input] of Object.entries(cases)){try{const r=run(input); failures[name]={status:'unexpected_success',artifact_hash:r.artifact.artifact_hash}}catch(e){failures[name]={status:'explicit_failure',error:e.message}}}
fs.writeFileSync('outputs/nex-verification/failure-matrix.json', JSON.stringify(failures,null,2));
const regression=runCanonicalVisualPipeline('why APIs fail at scale'); fs.writeFileSync('outputs/nex-verification/non-nex-result.json', JSON.stringify({status:regression.status,artifact_hash:regression.artifact.artifact_hash,slide_count:regression.artifact.slide_count,contract_hash:regression.render_contract.contract_hash},null,2));
console.log(JSON.stringify({valid:{artifact_hash:result.artifact.artifact_hash,slide_count:result.artifact.slide_count,path:'outputs/nex-verification/valid-nex-result.json'},determinism:runs,failures,regression:{artifact_hash:regression.artifact.artifact_hash,slide_count:regression.artifact.slide_count}},null,2));
